uploads = []
generated = []

[[outputs]]
id = "V1gm4fvuhbMU0vaPTWE8m"
uri = "file://jwani-accounting-system.zip"
type = "unspecified"
title = "ژوانی گەشتیاری — سیستەمی ژمێریاری (نوێکراوە)"

[[outputs]]
id = "wE4WBCgm50R-Bzpn8B9KY"
uri = "file://jwani_database_setup.zip"
type = "unspecified"
title = "jwani_database_setup.zip — داتابەیسی سیستەمی ژمێریاری"
